### PR TITLE
Update dogma and projectionkit

### PR DESCRIPTION
**Pull request by koden-km**
#### What change does this introduce?

This PR updates `dogma` and `projectionkit` libraries. The existing `account` and `customer` projections will be updated to use the new `NoCompactBehavior`. These projections currently have nothing to clean up during normal operation.

#### What issues does this relate to?

Fixes #78 

#### Why make this change?

This change will keep the example project up to date with the dogma apis.

#### Is there anything you are unsure about?

No.

### CODE REVIEW

**Comment by koden-km** [comment]
Actually, i'm not sure if this PR should say it Fixes the dependabot PR?

**Review by danilvpetrov — APPROVED** [review]
Looking quite straightforward.

**Review by jmalloc — APPROVED** [review]

**Comment by jmalloc** [comment]
> Actually, i'm not sure if this PR should say it Fixes the dependabot PR?

Nah, you can't "fix" a PR. Dependabot will close it's PR automatically when it sees that the dependencies have been updated.

**Comment by koden-km** [comment]
Apparently this did fix/close that other PR?

**Pull request merged**
