### PR TITLE
Prototype project structure by concept

### PR DESCRIPTION
**Pull request by koden-km**
This is the result of our recent discussion regarding grouping files by their concept. I don't know if this would end up being merged, but we wanted to see what the structure would look and feel like. As long as I didn't miss anything, then this is it, so discuss!

I didn't know what to call the root instance data structs, so i just named them `root` for now. I couldn't name them the same as the package itself. I guess `instance` may also be an ok name?

It is laid out like this:
```
aggregate/
	customer/
		handler.go
		root.go
	account/
		handler.go
		root.go
process/
	newcustomer/
		openaccount/
			handler.go
			root.go
	transaction/
		transfer/
			handler.go
			root.go
		withdraw/
			handler.go
			root.go
		deposit/
			handler.go
			root.go
message/
	command/
		account.go
		customer.go
	event/
		account.go
		customer.go
projection/
	...
integration/
	...
```

### CODE REVIEW

**Comment by jmalloc** [comment]
> I couldn't name them the same as the package itself

Are you sure?

**Comment by koden-km** [comment]
Doesn't that cause name conflict and/or stuttering?
```go
package account

type account struct {
}

...some other file...
a := account.account{}
```

**Comment by koden-km** [comment]
One thing with this setup is the number of extra `doc.go` files. I suppose they could be left out and the `handler.go` used as the default doc block file instead.

**Comment by jmalloc** [comment]
> One thing with this setup is the number of extra `doc.go` files. I suppose they could be left out and the `handler.go` used as the default doc block file instead.

I suppose, but files are cheap.. and it's likely in a more realistic application that there will be other files than just the handler and root in there... other value objects, etc.

> Doesn't that cause name conflict and/or stuttering?

The linter doesn't complain about `name.Name` only `name.NameSomething`.

**Comment by koden-km** [comment]
Ok I have given the `root` instance types names again. Seems to work fine and is nicer.

**Comment by koden-km** [comment]
Closing this as we have decided to go with the other flatter layout with a `domain` package for aggregates and processes. The domain package style requires less effort to setup and work on, and helps make it clear if/when your domain is getting too large to be a single thing.

**Pull request closed without merging**
