### PR TITLE
Split messages into separate packages for commands and events

### PR DESCRIPTION
**Pull request by koden-km**

### CODE REVIEW

**Comment by koden-km** [comment]
Something went weird with the PR. I only just cloned the repo and made a feature branch an hour ago. When pushing the PR here it tells me there is conflict, so i check master and sure enough there are changes from 5 hours ago...

**Comment by koden-km** [comment]
Ah hang on, now i see. Grit did find an existing clone, it just seemed like it was cloning fresh for some reason. All good. I'll fix this PR if i can figure out whats going on with go.mod

**Comment by jmalloc** [comment]
Did you clone with Grit? Is it possible you had an existing clone that grit found?

Yeah something is messed up, that Travis build failed because of a reference to `dogmatest` but I removed those earlier today.

**Comment by koden-km** [comment]
I had a left over reference to `dogamatest` in `main.go`.

**Pull request merged**
